# -*- coding: utf-8 -*-
"""Lam CSE420_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBZpgDDyI9xi5CrGcskpN1YGAlu1WAVH

### Md Abdun Fattah Lam (2220014)
     CSE420 (Section 1)
     Serial 18
     Assignment 1 - Autumn 2025

###importing library
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import os

"""###Mount with google drive"""

from google.colab import drive
drive.mount('/content/drive')

# Image Path in my drive
image_path = '/content/drive/MyDrive/AF/PIC.jpg'

img = cv2.imread(image_path)

print(f"Image shape: {img.shape} -(height, width, channels)")
#RGB value for one pixel
pixel_bgr = img[112, 112,0:3]
print(f"Pixel at ({112}, {112}) → BGR values: {pixel_bgr}") #BGR value for that pixel

b, g, r = pixel_bgr
print(f"R = {r}, G = {g}, B = {b}")

# Show the img
plt.imshow(img)
plt.title("PIC.jpg")
plt.axis('off')
plt.show()

# Show the img in RGB
# img_rgb1 = img[:, :, ::-1]   # using reverse [B, G, R] → [R, G, B]

img_rgb= img.copy()
img_rgb[:,:,0] = img[:,:,2]
img_rgb[:,:,1] = img[:,:,1]
img_rgb[:,:,2] = img[:,:,0]

plt.imshow(img_rgb)
plt.title("Manually Converted in Original")
plt.axis('off')
plt.show()

b,g,r = img[:,:,0],img[:,:,1],img[:,:,2]
plt.figure(figsize=(15,5))

plt.subplot(1, 3, 1) #Blue Channel
plt.imshow(b)
plt.title("Blue Channel")
plt.axis('off')

plt.subplot(1, 3, 2) #Green Channel
plt.imshow(g)
plt.title("Green Channel")
plt.axis('off')

plt.subplot(1, 3, 3) #Red Channel
plt.imshow(r)
plt.title("Red Channel")
plt.axis('off')

plt.show()

b,g,r = img[:,:,0],img[:,:,1],img[:,:,2]
plt.figure(figsize=(15,5))

plt.subplot(1, 3, 1) #Blue Channel
plt.imshow(b, cmap='gray')
plt.title("Blue Channel")
plt.axis('off')

plt.subplot(1, 3, 2) #Green Channel
plt.imshow(g, cmap='gray')
plt.title("Green Channel")
plt.axis('off')

plt.subplot(1, 3, 3) #Red Channel
plt.imshow(r, cmap='gray')
plt.title("Red Channel")
plt.axis('off')

plt.show()